### ISSUE TITLE
Run at 15:21 when the Dashboard is update with vaccination numbers

### ISSUE THREAD

**Issue by EwoutH** [mzelst/covid-19#30]
The dashboard lags just a few minutes behind data.rivm.nl, which means the webscraper got yesterdays vaccination data. Yesterday it was 163.931, today it's 173.638.

**Comment by EwoutH** [comment]
@mzelst Don't forget to check if the dashboard is updated before running the scripts today :)

**Comment by mzelst** [comment]
Hi Ewout,

Luckily, the dashboard got updated and the source data for vaccines seems to be updated earlier than the actual dashboard is updated :) So we're now using the actual numbers of today that are also displayed on the dashboard (around 15:20) in the daily update. Thanks for your note!

**Comment by EwoutH** [comment]
The current value still is yesterdays value (185.356, on January 27th), it will update again today around 15:20. So by running the scripts at 15:16 you will miss the updated value again and keep lagging a day behind.

**Comment by mzelst** [comment]
Hi Ewout, 

Yeah, I've misread the documentation for the source code and read vaccines delivery expected as vaccines used. Rewriting the code again so it fully works. 

The quick update is finding a balance between accuracy and being the first. Perhaps good to move the scheduled update until 15:20 (instead of 15:15) until they properly fix the open data (it's the worst here). Thanks for being sharp!

**Comment by EwoutH** [comment]
Let's hope the vaccination data will soon be updated at data.rivm.nl.

Thanks for the amazing reports every day!
